In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nasdaq_tesla_stock_data.csv")

In [3]:
df

,Unnamed: 0,Date,Close/Last,Volume,Open,High,Low
0,1,02/14/2023,$209.25,"216,455,700",$191.94,$209.82,$189.44
1,2,02/13/2023,$194.64,"172,475,500",$194.415,$196.3,$187.61
2,3,02/10/2023,$196.89,"204,754,100",$202.225,$206.2,$192.89
3,4,02/09/2023,$207.32,"215,431,400",$207.775,$214,$204.77
4,5,02/08/2023,$201.29,"180,673,600",$196.1,$203,$194.31
...,...,...,...,...,...,...,...
122,129,08/19/2022,$296.6666,"61,395,396",$299,$300.36,$292.5
123,130,08/18/2022,$302.87,"47,500,535",$306,$306.5,$301.8533
124,131,08/17/2022,$303.9966,"68,765,977",$303.3966,$309.6566,$300.0333
125,132,08/16/2022,$306.5633,"88,136,319",$311.6666,$314.6666,$302.8833
126,134,08/15/2022,$309.32,"89,359,179",$301.7866,$313.1333,$301.23

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
df

           Date Close/Last       Volume       Open       High        Low
0    02/14/2023    $209.25  216,455,700    $191.94    $209.82    $189.44
1    02/13/2023    $194.64  172,475,500   $194.415     $196.3    $187.61
2    02/10/2023    $196.89  204,754,100   $202.225     $206.2    $192.89
3    02/09/2023    $207.32  215,431,400   $207.775       $214    $204.77
4    02/08/2023    $201.29  180,673,600     $196.1       $203    $194.31
..          ...        ...          ...        ...        ...        ...
122  08/19/2022  $296.6666   61,395,396       $299    $300.36     $292.5
123  08/18/2022    $302.87   47,500,535       $306     $306.5  $301.8533
124  08/17/2022  $303.9966   68,765,977  $303.3966  $309.6566  $300.0333
125  08/16/2022  $306.5633   88,136,319  $311.6666  $314.6666  $302.8833
126  08/15/2022    $309.32   89,359,179  $301.7866  $313.1333    $301.23

[127 rows x 6 columns]

In [6]:
pd.options.display.max_rows = None

In [7]:
df

           Date Close/Last       Volume       Open       High        Low
0    02/14/2023    $209.25  216,455,700    $191.94    $209.82    $189.44
1    02/13/2023    $194.64  172,475,500   $194.415     $196.3    $187.61
2    02/10/2023    $196.89  204,754,100   $202.225     $206.2    $192.89
3    02/09/2023    $207.32  215,431,400   $207.775       $214    $204.77
4    02/08/2023    $201.29  180,673,600     $196.1       $203    $194.31
5    02/07/2023    $196.81  186,010,300    $196.43     $197.5    $189.55
6    02/06/2023    $194.76  186,188,100    $193.01    $198.17    $189.92
7    02/03/2023    $189.98  232,662,000    $183.95       $199    $183.69
8    02/02/2023    $188.27  217,448,300   $187.325  $196.7501    $182.61
9    02/01/2023    $181.41  213,806,300    $173.89   $183.805    $169.93
10   01/31/2023    $173.22  196,813,500    $164.57     $174.3    $162.78
11   01/30/2023    $166.66  230,878,800    $178.05    $179.77     $166.5
12   01/27/2023     $177.9  306,590,600    $162.43    $180.68    $161.17
13   01/26/2023    $160.27  234,815,100   $159.965    $161.42    $154.76
14   01/25/2023    $144.43  192,734,300   $141.905    $146.41    $138.07
15   01/24/2023    $143.89  158,699,100       $143     $146.5     $141.1
16   01/23/2023    $143.75  203,119,200    $135.87  $145.3793    $134.27
17   01/20/2023    $133.42  138,858,100    $128.68    $133.51  $127.3466
18   01/19/2023    $127.17  170,291,900    $127.26    $129.99  $124.3082
19   01/18/2023    $128.78  195,680,300   $136.555    $136.68    $127.01
20   01/17/2023    $131.49  186,477,000   $125.695     $131.7    $125.02
21   01/13/2023     $122.4  180,714,100    $116.55    $122.63     $115.6
22   01/12/2023    $123.56  169,400,900    $122.56  $124.1311       $117
23   01/11/2023    $123.22  183,810,800    $122.09    $125.95    $120.51
24   01/10/2023    $118.85  167,642,500    $121.07    $122.76    $114.92
25   01/09/2023    $119.77  190,284,000    $118.96    $123.52    $117.11
26   01/06/2023    $113.06  220,911,100       $103    $114.39    $101.81
27   01/05/2023    $110.34  157,986,300    $110.51    $111.75  $107.1601
28   01/04/2023    $113.64  180,389,000    $109.11    $114.59    $107.52
29   01/03/2023     $108.1  231,402,800    $118.47     $118.8    $104.64
30   12/30/2022    $123.18  157,777,300    $119.95    $124.48    $119.75
31   12/29/2022    $121.82  221,923,300   $120.385    $123.57   $117.495
32   12/28/2022    $112.71  221,070,500    $110.35    $116.27    $108.24
33   12/27/2022     $109.1  208,643,400   $117.495    $119.67    $108.76
34   12/23/2022    $123.15  166,989,700    $126.37  $128.6173    $121.02
35   12/22/2022    $125.35  210,090,300       $136    $136.63    $122.26
36   12/21/2022    $137.57  145,417,400   $139.335    $141.26    $135.89
37   12/20/2022     $137.8  159,563,300    $146.05    $148.47    $137.66
38   12/19/2022    $149.87  139,390,600       $154    $155.25    $145.82
39   12/16/2022    $150.23  139,032,200   $159.635    $160.99    $150.04
40   12/15/2022    $157.67  122,334,500    $153.44  $160.9299    $153.28
41   12/14/2022     $156.8  140,682,300    $159.25    $161.62    $155.31
42   12/13/2022    $160.95  175,862,700    $174.87    $175.05    $156.91
43   12/12/2022    $167.82  109,794,500     $176.1    $177.37    $167.52
44   12/09/2022    $179.05  104,872,300    $173.84     $182.5    $173.36
45   12/08/2022    $173.44   97,624,490     $172.2     $175.2    $169.06
46   12/07/2022    $174.04   84,213,280    $175.03    $179.38   $172.218
47   12/06/2022    $179.82   92,150,820   $181.215    $183.65    $175.33
48   12/05/2022    $182.45   93,122,670    $189.44    $191.27    $180.55
49   12/02/2022    $194.86   73,645,920    $191.78    $196.25    $191.11
50   12/01/2022     $194.7   80,046,210    $197.08    $198.92     $191.8
51   11/30/2022     $194.7  109,186,400    $182.43    $194.76  $180.6301
52   11/29/2022    $180.83   83,357,110    $184.99    $186.38    $178.75
53   11/28/2022    $182.92   93,038,150    $179.96     $188.5       $179
54   11/25/2022    $182.86   50,672,740    $185.06     $185.2    $180.63
55   11/23/2022     $183.2  109,536,700    $173.57    $183.62     $172.5
56   11/22/2022    $169.91   78,452,330    $168.63    $170.92   $166.185
57   11/21/2022    $167.87   92,882,710    $175.85    $176.77    $167.54
58   11/18/2022    $180.19   76,048,870    $185.05    $185.19    $176.55
59   11/17/2022    $183.17   64,335,970    $183.96    $186.16     $180.9
60   11/16/2022    $186.92   66,567,600    $191.51    $192.57    $185.66
61   11/15/2022    $194.42   91,293,790    $195.88  $200.8237    $192.06
62   11/14/2022    $190.95   92,226,650    $192.77    $195.73    $186.34
63   11/11/2022    $195.97  114,403,600       $186    $196.52    $182.59
64   11/10/2022    $190.72  132,703,000     $189.9       $191    $180.03
65   11/09/2022    $177.59  127,062,700   $190.775    $195.89    $177.12
66   11/08/2022     $191.3  128,803,400    $194.02     $195.2    $186.75
67   11/07/2022    $197.08   93,916,520    $208.65     $208.9    $196.66
68   11/04/2022    $207.47   98,622,210     $222.6     $223.8    $203.08
69   11/03/2022    $215.31   56,538,850    $211.36     $221.2    $210.14
70   11/02/2022    $214.98   63,070,290    $226.04  $227.8699    $214.82
71   11/01/2022    $227.82   62,688,820    $234.05  $237.3951    $227.28
72   10/31/2022    $227.54   61,554,340    $226.19    $229.85    $221.94
73   10/28/2022    $228.52   69,152,390     $225.4    $228.86    $216.35
74   10/27/2022    $225.09   61,638,820    $229.77    $233.81    $222.85
75   10/26/2022    $224.64   85,327,080     $219.4     $230.6     $218.2
76   10/25/2022   $222.415   96,507,870     $210.1  $224.3498       $210
77   10/24/2022    $211.25  100,446,800    $205.82     $213.5  $198.5863
78   10/21/2022    $214.44   75,713,750   $206.415    $214.66     $203.8
79   10/20/2022    $207.28  117,798,100    $208.28    $215.55       $202
80   10/19/2022    $222.04   66,571,480     $219.8    $222.93    $217.78
81   10/18/2022    $220.19   75,891,910     $229.5    $229.82    $217.25
82   10/17/2022    $219.35   79,428,810    $210.04    $221.86    $209.45
83   10/14/2022    $204.99   94,124,510    $224.01    $226.26    $204.16
84   10/13/2022    $221.72   91,483,050     $208.3    $222.99    $206.22
85   10/12/2022    $217.24   66,860,700    $215.33  $219.2999    $211.51
86   10/11/2022     $216.5   77,013,200   $220.945    $225.75       $215
87   10/10/2022    $222.96   67,925,020    $223.93    $226.99  $218.3582
88   10/07/2022    $223.07   83,916,800   $233.935  $234.5715    $222.02
89   10/06/2022    $238.13   69,298,440    $239.44    $244.58    $235.35
90   10/05/2022    $240.81   86,982,670    $245.01  $246.6697    $233.27
91   10/04/2022    $249.44  109,578,500    $250.52     $257.5    $242.01
92   10/03/2022     $242.4   98,363,540     $254.5    $255.16    $241.01
93   09/30/2022    $265.25   67,726,600   $266.145    $275.57    $262.47
94   09/29/2022    $268.21   77,620,640    $282.76    $283.65    $265.78
95   09/28/2022    $287.81   54,664,810    $283.08       $289    $277.57
96   09/27/2022    $282.94   61,925,190    $283.84    $288.67    $277.51
97   09/26/2022    $276.01   58,076,910    $271.83    $284.09    $270.31
98   09/23/2022    $275.33   63,748,360    $283.09     $284.5    $272.82
99   09/22/2022    $288.59   70,545,410    $299.86    $301.29    $285.82
100  09/21/2022     $300.8   62,555,660    $308.29     $313.8    $300.63
101  09/20/2022    $308.73   61,642,780    $306.91    $313.33    $305.58
102  09/19/2022    $309.07   60,231,160    $300.09    $309.84     $297.8
103  09/16/2022    $303.35   87,087,790   $299.605    $303.71  $295.6005
104  09/15/2022    $303.75   64,795,520   $301.825    $309.12  $300.7247
105  09/14/2022    $302.61   72,628,650    $292.24       $306    $291.64
106  09/13/2022    $292.13   68,229,620     $292.9  $297.3999     $290.4
107  09/12/2022    $304.42   48,674,600    $300.72    $305.49     $300.4
108  09/09/2022    $299.68   54,470,850    $291.67    $299.85   $291.245
109  09/08/2022    $289.26   53,713,120     $281.3     $289.5    $279.76
110  09/07/2022     $283.7   50,028,920     $273.1    $283.84    $272.27
111  09/06/2022    $274.42   55,859,980   $272.675    $275.99    $265.74
112  09/02/2022    $270.21   50,890,090   $281.065    $282.35    $269.08
113  09/01/2022    $277.16   54,287,020   $272.575    $277.58    $266.15
114  08/31/2022    $275.61   52,107,340    $280.62    $281.25    $271.81
115  08/30/2022     $277.7   50,541,760   $287.865    $288.48    $272.65
116  08/29/2022    $284.82   41,864,740    $282.83    $287.74     $280.7
117  08/26/2022    $288.09   57,163,950    $297.43       $302    $287.47
118  08/25/2022    $296.07   53,230,010    $302.36    $302.96     $291.6
119  08/24/2022  $297.0966   57,259,716  $297.5633  $303.6466     $296.5
120  08/23/2022  $296.4533   63,985,056  $291.4533  $298.8266  $287.9233
121  08/22/2022  $289.9133   55,843,356  $291.9133     $292.4  $286.2966
122  08/19/2022  $296.6666   61,395,396       $299    $300.36     $292.5
123  08/18/2022    $302.87   47,500,535       $306     $306.5  $301.8533
124  08/17/2022  $303.9966   68,765,977  $303.3966  $309.6566  $300.0333
125  08/16/2022  $306.5633   88,136,319  $311.6666  $314.6666  $302.8833
126  08/15/2022    $309.32   89,359,179  $301.7866  $313.1333    $301.23

In [13]:
df.dtypes

Date          datetime64[ns]
Close/Last            object
Volume                object
Open                  object
High                  object
Low                   object
dtype: object

In [12]:
df['Date'] = pd.to_datetime(df['Date'])

# |

In [14]:
# Drop the '$' sign and convert the columns to float data type
df['Close/Last'] = df['Close/Last'].str.replace('$', '').astype(float)
df['Open'] = df['Open'].str.replace('$', '').astype(float)
df['High'] = df['High'].str.replace('$', '').astype(float)
df['Low'] = df['Low'].str.replace('$', '').astype(float)

/var/folders/lc/wd3z5xrd5s7cbp_lm8v3mkdm0000gn/T/ipykernel_10575/4037009723.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Close/Last'] = df['Close/Last'].str.replace('$', '').astype(float)
/var/folders/lc/wd3z5xrd5s7cbp_lm8v3mkdm0000gn/T/ipykernel_10575/4037009723.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Open'] = df['Open'].str.replace('$', '').astype(float)
/var/folders/lc/wd3z5xrd5s7cbp_lm8v3mkdm0000gn/T/ipykernel_10575/4037009723.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['High'] = df['High'].str.replace('$', '').astype(float)
/var/folders/lc/wd3z5xrd5s7cbp_lm8v3mkdm0000gn/T/ipykernel_10575/4037009723.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Low'] = df['Low'].str.replace('$', '').astype(float)

In [15]:
df

          Date  Close/Last       Volume      Open      High       Low
0   2023-02-14    209.2500  216,455,700  191.9400  209.8200  189.4400
1   2023-02-13    194.6400  172,475,500  194.4150  196.3000  187.6100
2   2023-02-10    196.8900  204,754,100  202.2250  206.2000  192.8900
3   2023-02-09    207.3200  215,431,400  207.7750  214.0000  204.7700
4   2023-02-08    201.2900  180,673,600  196.1000  203.0000  194.3100
5   2023-02-07    196.8100  186,010,300  196.4300  197.5000  189.5500
6   2023-02-06    194.7600  186,188,100  193.0100  198.1700  189.9200
7   2023-02-03    189.9800  232,662,000  183.9500  199.0000  183.6900
8   2023-02-02    188.2700  217,448,300  187.3250  196.7501  182.6100
9   2023-02-01    181.4100  213,806,300  173.8900  183.8050  169.9300
10  2023-01-31    173.2200  196,813,500  164.5700  174.3000  162.7800
11  2023-01-30    166.6600  230,878,800  178.0500  179.7700  166.5000
12  2023-01-27    177.9000  306,590,600  162.4300  180.6800  161.1700
13  2023-01-26    160.2700  234,815,100  159.9650  161.4200  154.7600
14  2023-01-25    144.4300  192,734,300  141.9050  146.4100  138.0700
15  2023-01-24    143.8900  158,699,100  143.0000  146.5000  141.1000
16  2023-01-23    143.7500  203,119,200  135.8700  145.3793  134.2700
17  2023-01-20    133.4200  138,858,100  128.6800  133.5100  127.3466
18  2023-01-19    127.1700  170,291,900  127.2600  129.9900  124.3082
19  2023-01-18    128.7800  195,680,300  136.5550  136.6800  127.0100
20  2023-01-17    131.4900  186,477,000  125.6950  131.7000  125.0200
21  2023-01-13    122.4000  180,714,100  116.5500  122.6300  115.6000
22  2023-01-12    123.5600  169,400,900  122.5600  124.1311  117.0000
23  2023-01-11    123.2200  183,810,800  122.0900  125.9500  120.5100
24  2023-01-10    118.8500  167,642,500  121.0700  122.7600  114.9200
25  2023-01-09    119.7700  190,284,000  118.9600  123.5200  117.1100
26  2023-01-06    113.0600  220,911,100  103.0000  114.3900  101.8100
27  2023-01-05    110.3400  157,986,300  110.5100  111.7500  107.1601
28  2023-01-04    113.6400  180,389,000  109.1100  114.5900  107.5200
29  2023-01-03    108.1000  231,402,800  118.4700  118.8000  104.6400
30  2022-12-30    123.1800  157,777,300  119.9500  124.4800  119.7500
31  2022-12-29    121.8200  221,923,300  120.3850  123.5700  117.4950
32  2022-12-28    112.7100  221,070,500  110.3500  116.2700  108.2400
33  2022-12-27    109.1000  208,643,400  117.4950  119.6700  108.7600
34  2022-12-23    123.1500  166,989,700  126.3700  128.6173  121.0200
35  2022-12-22    125.3500  210,090,300  136.0000  136.6300  122.2600
36  2022-12-21    137.5700  145,417,400  139.3350  141.2600  135.8900
37  2022-12-20    137.8000  159,563,300  146.0500  148.4700  137.6600
38  2022-12-19    149.8700  139,390,600  154.0000  155.2500  145.8200
39  2022-12-16    150.2300  139,032,200  159.6350  160.9900  150.0400
40  2022-12-15    157.6700  122,334,500  153.4400  160.9299  153.2800
41  2022-12-14    156.8000  140,682,300  159.2500  161.6200  155.3100
42  2022-12-13    160.9500  175,862,700  174.8700  175.0500  156.9100
43  2022-12-12    167.8200  109,794,500  176.1000  177.3700  167.5200
44  2022-12-09    179.0500  104,872,300  173.8400  182.5000  173.3600
45  2022-12-08    173.4400   97,624,490  172.2000  175.2000  169.0600
46  2022-12-07    174.0400   84,213,280  175.0300  179.3800  172.2180
47  2022-12-06    179.8200   92,150,820  181.2150  183.6500  175.3300
48  2022-12-05    182.4500   93,122,670  189.4400  191.2700  180.5500
49  2022-12-02    194.8600   73,645,920  191.7800  196.2500  191.1100
50  2022-12-01    194.7000   80,046,210  197.0800  198.9200  191.8000
51  2022-11-30    194.7000  109,186,400  182.4300  194.7600  180.6301
52  2022-11-29    180.8300   83,357,110  184.9900  186.3800  178.7500
53  2022-11-28    182.9200   93,038,150  179.9600  188.5000  179.0000
54  2022-11-25    182.8600   50,672,740  185.0600  185.2000  180.6300
55  2022-11-23    183.2000  109,536,700  173.5700  183.6200  172.5000
56  2022-11-22    169.9100   78,452,330  168.6300  170.9200  166.1850
57  2022-11-21    167.8700   92,882,710  175.8500  176.7700  167.5400
58  2022-11-18    180.1900   76,048,870  185.0500  185.1900  176.5500
59  2022-11-17    183.1700   64,335,970  183.9600  186.1600  180.9000
60  2022-11-16    186.9200   66,567,600  191.5100  192.5700  185.6600
61  2022-11-15    194.4200   91,293,790  195.8800  200.8237  192.0600
62  2022-11-14    190.9500   92,226,650  192.7700  195.7300  186.3400
63  2022-11-11    195.9700  114,403,600  186.0000  196.5200  182.5900
64  2022-11-10    190.7200  132,703,000  189.9000  191.0000  180.0300
65  2022-11-09    177.5900  127,062,700  190.7750  195.8900  177.1200
66  2022-11-08    191.3000  128,803,400  194.0200  195.2000  186.7500
67  2022-11-07    197.0800   93,916,520  208.6500  208.9000  196.6600
68  2022-11-04    207.4700   98,622,210  222.6000  223.8000  203.0800
69  2022-11-03    215.3100   56,538,850  211.3600  221.2000  210.1400
70  2022-11-02    214.9800   63,070,290  226.0400  227.8699  214.8200
71  2022-11-01    227.8200   62,688,820  234.0500  237.3951  227.2800
72  2022-10-31    227.5400   61,554,340  226.1900  229.8500  221.9400
73  2022-10-28    228.5200   69,152,390  225.4000  228.8600  216.3500
74  2022-10-27    225.0900   61,638,820  229.7700  233.8100  222.8500
75  2022-10-26    224.6400   85,327,080  219.4000  230.6000  218.2000
76  2022-10-25    222.4150   96,507,870  210.1000  224.3498  210.0000
77  2022-10-24    211.2500  100,446,800  205.8200  213.5000  198.5863
78  2022-10-21    214.4400   75,713,750  206.4150  214.6600  203.8000
79  2022-10-20    207.2800  117,798,100  208.2800  215.5500  202.0000
80  2022-10-19    222.0400   66,571,480  219.8000  222.9300  217.7800
81  2022-10-18    220.1900   75,891,910  229.5000  229.8200  217.2500
82  2022-10-17    219.3500   79,428,810  210.0400  221.8600  209.4500
83  2022-10-14    204.9900   94,124,510  224.0100  226.2600  204.1600
84  2022-10-13    221.7200   91,483,050  208.3000  222.9900  206.2200
85  2022-10-12    217.2400   66,860,700  215.3300  219.2999  211.5100
86  2022-10-11    216.5000   77,013,200  220.9450  225.7500  215.0000
87  2022-10-10    222.9600   67,925,020  223.9300  226.9900  218.3582
88  2022-10-07    223.0700   83,916,800  233.9350  234.5715  222.0200
89  2022-10-06    238.1300   69,298,440  239.4400  244.5800  235.3500
90  2022-10-05    240.8100   86,982,670  245.0100  246.6697  233.2700
91  2022-10-04    249.4400  109,578,500  250.5200  257.5000  242.0100
92  2022-10-03    242.4000   98,363,540  254.5000  255.1600  241.0100
93  2022-09-30    265.2500   67,726,600  266.1450  275.5700  262.4700
94  2022-09-29    268.2100   77,620,640  282.7600  283.6500  265.7800
95  2022-09-28    287.8100   54,664,810  283.0800  289.0000  277.5700
96  2022-09-27    282.9400   61,925,190  283.8400  288.6700  277.5100
97  2022-09-26    276.0100   58,076,910  271.8300  284.0900  270.3100
98  2022-09-23    275.3300   63,748,360  283.0900  284.5000  272.8200
99  2022-09-22    288.5900   70,545,410  299.8600  301.2900  285.8200
100 2022-09-21    300.8000   62,555,660  308.2900  313.8000  300.6300
101 2022-09-20    308.7300   61,642,780  306.9100  313.3300  305.5800
102 2022-09-19    309.0700   60,231,160  300.0900  309.8400  297.8000
103 2022-09-16    303.3500   87,087,790  299.6050  303.7100  295.6005
104 2022-09-15    303.7500   64,795,520  301.8250  309.1200  300.7247
105 2022-09-14    302.6100   72,628,650  292.2400  306.0000  291.6400
106 2022-09-13    292.1300   68,229,620  292.9000  297.3999  290.4000
107 2022-09-12    304.4200   48,674,600  300.7200  305.4900  300.4000
108 2022-09-09    299.6800   54,470,850  291.6700  299.8500  291.2450
109 2022-09-08    289.2600   53,713,120  281.3000  289.5000  279.7600
110 2022-09-07    283.7000   50,028,920  273.1000  283.8400  272.2700
111 2022-09-06    274.4200   55,859,980  272.6750  275.9900  265.7400
112 2022-09-02    270.2100   50,890,090  281.0650  282.3500  269.0800
113 2022-09-01    277.1600   54,287,020  272.5750  277.5800  266.1500
114 2022-08-31    275.6100   52,107,340  280.6200  281.2500  271.8100
115 2022-08-30    277.7000   50,541,760  287.8650  288.4800  272.6500
116 2022-08-29    284.8200   41,864,740  282.8300  287.7400  280.7000
117 2022-08-26    288.0900   57,163,950  297.4300  302.0000  287.4700
118 2022-08-25    296.0700   53,230,010  302.3600  302.9600  291.6000
119 2022-08-24    297.0966   57,259,716  297.5633  303.6466  296.5000
120 2022-08-23    296.4533   63,985,056  291.4533  298.8266  287.9233
121 2022-08-22    289.9133   55,843,356  291.9133  292.4000  286.2966
122 2022-08-19    296.6666   61,395,396  299.0000  300.3600  292.5000
123 2022-08-18    302.8700   47,500,535  306.0000  306.5000  301.8533
124 2022-08-17    303.9966   68,765,977  303.3966  309.6566  300.0333
125 2022-08-16    306.5633   88,136,319  311.6666  314.6666  302.8833
126 2022-08-15    309.3200   89,359,179  301.7866  313.1333  301.2300

In [16]:
df.dtypes

Date          datetime64[ns]
Close/Last           float64
Volume                object
Open                 float64
High                 float64
Low                  float64
dtype: object

In [17]:
df_new = df[['Date', 'Close/Last']]

In [18]:
df_new

          Date  Close/Last
0   2023-02-14    209.2500
1   2023-02-13    194.6400
2   2023-02-10    196.8900
3   2023-02-09    207.3200
4   2023-02-08    201.2900
5   2023-02-07    196.8100
6   2023-02-06    194.7600
7   2023-02-03    189.9800
8   2023-02-02    188.2700
9   2023-02-01    181.4100
10  2023-01-31    173.2200
11  2023-01-30    166.6600
12  2023-01-27    177.9000
13  2023-01-26    160.2700
14  2023-01-25    144.4300
15  2023-01-24    143.8900
16  2023-01-23    143.7500
17  2023-01-20    133.4200
18  2023-01-19    127.1700
19  2023-01-18    128.7800
20  2023-01-17    131.4900
21  2023-01-13    122.4000
22  2023-01-12    123.5600
23  2023-01-11    123.2200
24  2023-01-10    118.8500
25  2023-01-09    119.7700
26  2023-01-06    113.0600
27  2023-01-05    110.3400
28  2023-01-04    113.6400
29  2023-01-03    108.1000
30  2022-12-30    123.1800
31  2022-12-29    121.8200
32  2022-12-28    112.7100
33  2022-12-27    109.1000
34  2022-12-23    123.1500
35  2022-12-22    125.3500
36  2022-12-21    137.5700
37  2022-12-20    137.8000
38  2022-12-19    149.8700
39  2022-12-16    150.2300
40  2022-12-15    157.6700
41  2022-12-14    156.8000
42  2022-12-13    160.9500
43  2022-12-12    167.8200
44  2022-12-09    179.0500
45  2022-12-08    173.4400
46  2022-12-07    174.0400
47  2022-12-06    179.8200
48  2022-12-05    182.4500
49  2022-12-02    194.8600
50  2022-12-01    194.7000
51  2022-11-30    194.7000
52  2022-11-29    180.8300
53  2022-11-28    182.9200
54  2022-11-25    182.8600
55  2022-11-23    183.2000
56  2022-11-22    169.9100
57  2022-11-21    167.8700
58  2022-11-18    180.1900
59  2022-11-17    183.1700
60  2022-11-16    186.9200
61  2022-11-15    194.4200
62  2022-11-14    190.9500
63  2022-11-11    195.9700
64  2022-11-10    190.7200
65  2022-11-09    177.5900
66  2022-11-08    191.3000
67  2022-11-07    197.0800
68  2022-11-04    207.4700
69  2022-11-03    215.3100
70  2022-11-02    214.9800
71  2022-11-01    227.8200
72  2022-10-31    227.5400
73  2022-10-28    228.5200
74  2022-10-27    225.0900
75  2022-10-26    224.6400
76  2022-10-25    222.4150
77  2022-10-24    211.2500
78  2022-10-21    214.4400
79  2022-10-20    207.2800
80  2022-10-19    222.0400
81  2022-10-18    220.1900
82  2022-10-17    219.3500
83  2022-10-14    204.9900
84  2022-10-13    221.7200
85  2022-10-12    217.2400
86  2022-10-11    216.5000
87  2022-10-10    222.9600
88  2022-10-07    223.0700
89  2022-10-06    238.1300
90  2022-10-05    240.8100
91  2022-10-04    249.4400
92  2022-10-03    242.4000
93  2022-09-30    265.2500
94  2022-09-29    268.2100
95  2022-09-28    287.8100
96  2022-09-27    282.9400
97  2022-09-26    276.0100
98  2022-09-23    275.3300
99  2022-09-22    288.5900
100 2022-09-21    300.8000
101 2022-09-20    308.7300
102 2022-09-19    309.0700
103 2022-09-16    303.3500
104 2022-09-15    303.7500
105 2022-09-14    302.6100
106 2022-09-13    292.1300
107 2022-09-12    304.4200
108 2022-09-09    299.6800
109 2022-09-08    289.2600
110 2022-09-07    283.7000
111 2022-09-06    274.4200
112 2022-09-02    270.2100
113 2022-09-01    277.1600
114 2022-08-31    275.6100
115 2022-08-30    277.7000
116 2022-08-29    284.8200
117 2022-08-26    288.0900
118 2022-08-25    296.0700
119 2022-08-24    297.0966
120 2022-08-23    296.4533
121 2022-08-22    289.9133
122 2022-08-19    296.6666
123 2022-08-18    302.8700
124 2022-08-17    303.9966
125 2022-08-16    306.5633
126 2022-08-15    309.3200

In [21]:
df_new.to_csv("stocktesla.csv")

In [22]:
df_updated = df_new.drop(index=df.index[65:])

In [23]:
df_updated

         Date  Close/Last
0  2023-02-14      209.25
1  2023-02-13      194.64
2  2023-02-10      196.89
3  2023-02-09      207.32
4  2023-02-08      201.29
5  2023-02-07      196.81
6  2023-02-06      194.76
7  2023-02-03      189.98
8  2023-02-02      188.27
9  2023-02-01      181.41
10 2023-01-31      173.22
11 2023-01-30      166.66
12 2023-01-27      177.90
13 2023-01-26      160.27
14 2023-01-25      144.43
15 2023-01-24      143.89
16 2023-01-23      143.75
17 2023-01-20      133.42
18 2023-01-19      127.17
19 2023-01-18      128.78
20 2023-01-17      131.49
21 2023-01-13      122.40
22 2023-01-12      123.56
23 2023-01-11      123.22
24 2023-01-10      118.85
25 2023-01-09      119.77
26 2023-01-06      113.06
27 2023-01-05      110.34
28 2023-01-04      113.64
29 2023-01-03      108.10
30 2022-12-30      123.18
31 2022-12-29      121.82
32 2022-12-28      112.71
33 2022-12-27      109.10
34 2022-12-23      123.15
35 2022-12-22      125.35
36 2022-12-21      137.57
37 2022-12-20      137.80
38 2022-12-19      149.87
39 2022-12-16      150.23
40 2022-12-15      157.67
41 2022-12-14      156.80
42 2022-12-13      160.95
43 2022-12-12      167.82
44 2022-12-09      179.05
45 2022-12-08      173.44
46 2022-12-07      174.04
47 2022-12-06      179.82
48 2022-12-05      182.45
49 2022-12-02      194.86
50 2022-12-01      194.70
51 2022-11-30      194.70
52 2022-11-29      180.83
53 2022-11-28      182.92
54 2022-11-25      182.86
55 2022-11-23      183.20
56 2022-11-22      169.91
57 2022-11-21      167.87
58 2022-11-18      180.19
59 2022-11-17      183.17
60 2022-11-16      186.92
61 2022-11-15      194.42
62 2022-11-14      190.95
63 2022-11-11      195.97
64 2022-11-10      190.72

In [24]:
df_updated.to_csv("stockteslaupdated.csv")